# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tartarosbottiv2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DA1DE95AA44B4841AAE0D652AE8A9FC3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_935AF8BB59DE4AFBAED15F2919F620F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0A3D28CD1D784F838E1242487D7C5842 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tartarosbottiv2'
          slot-name: 'Production'
          package: .
          
      - name: 'Set Application Settings in Azure Web App'
        run: |
          az webapp config appsettings set --name ${{ secrets.AZURE_APP_NAME }} --resource-group ${{ secrets.AZURE_RG_NAME }} --settings MONGO_URL_PROD="${{ secrets.MONGO_URL_PROD }}" BOT_ID_PROD="${{ secrets.BOT_ID_PROD }}" ENCRYPT_PASS="${{ secrets.ENCRYPT_PASS }}" ENVIRONMENT="${{ secrets.ENVIRONMENT }}" NOTIFICATIONS_ENABLED="${{ secrets.NOTIFICATIONS_ENABLED }}" SALT="${{ secrets.SALT }}" STREAM_NOTIFICATION_CHANNEL_PROD="${{ secrets.STREAM_NOTIFICATION_CHANNEL_PROD }}" TARTAROS_NOTIFICATIONS="${{ secrets.TARTAROS_NOTIFICATIONS }}" TOKEN_SECRET="${{ secrets.TOKEN_SECRET }}" TWITCH_CLIENT_ID="${{ secrets.TWITCH_CLIENT_ID }}" TWITCH_CLIENT_SECRET="${{ secrets.TWITCH_CLIENT_SECRET }}" GUILD_ID_PROD="${{ secrets.GUILD_ID_PROD }}" BOT_TOKEN_PROD="${{ secrets.BOT_TOKEN_PROD }}"
